---
title: "flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
data('instacart')
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
ins_department <- instacart %>%
  group_by(user_id) %>% 
  select(order_id, department, user_id, reordered, order_number,add_to_cart_order) %>% 
  filter(reordered == 1) %>%
  filter(order_id <= 10000)

ins_department %>% 
  plot_ly(x = ~ department, y = ~ order_number, type = "scatter", color = ~ order_number)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
ins_department %>%
  mutate(department = fct_reorder(department, order_number)) %>%
  plot_ly(y = ~order_number, color = ~department, type = "box")
```

### Chart C

```{r}
ins_department %>%
  count(department) %>%
  mutate(department = fct_reorder(department, n)) |> 
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar", colors = "viridis")
```



